name = "SMLMMetrics"
uuid = "0dae9b29-4590-421e-953b-e41aa0457150"
authors = ["klidke@unm.edu"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
